// pdf/renderLetterHtml.js
function escapeHtml(s = "") {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function nl2br(s = "") {
  return escapeHtml(s).replaceAll("\n", "<br/>");
}

function renderLetterHtml({ letter, letterheadFileUrl }) {
  // letterheadFileUrl will be a file:///... URL (works reliably in puppeteer)
  return `
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: A4; margin: 18mm 18mm 18mm 18mm; }
    body { font-family: Arial, Helvetica, sans-serif; font-size: 11pt; color: #111; }
    .letterhead { width: 100%; height: auto; margin-bottom: 10mm; }
    .row { margin-bottom: 6mm; }
    .right { text-align: right; }
    .block { white-space: normal; line-height: 1.35; }
    .reline { font-weight: bold; margin-top: 6mm; }
    .greeting { margin-top: 6mm; }
    .body { margin-top: 4mm; }
    .closing { margin-top: 6mm; }
    .signoff { margin-top: 10mm; }
    .signature-placeholder { margin-top: 14mm; color: #666; }
    hr.footerline { margin-top: 12mm; border: none; border-top: 1px solid #ddd; }
    .footer { font-size: 9pt; color: #666; margin-top: 3mm; }
  </style>
</head>
<body>
  <img class="letterhead" src="${letterheadFileUrl}" alt="Letterhead"/>

  <div class="row right">${escapeHtml(letter.letter_date)}</div>

  <div class="row block">${nl2br(letter.referrer_block)}</div>

  <div class="row reline">${escapeHtml(letter.patient_re_line)}</div>

  <div class="row greeting">${escapeHtml(letter.greeting)}</div>

  <div class="row body block">${nl2br(letter.body_text)}</div>

  <div class="row closing block">${nl2br(letter.closing_text)}</div>

  <div class="row signoff">
    Kind regards,<br/>
    <div class="signature-placeholder">[Signature block â add in next iteration]</div>
  </div>

  <hr class="footerline"/>
  <div class="footer">Generated by Referral PoC</div>
</body>
</html>
`;
}

module.exports = { renderLetterHtml };